# Generated by Django 5.2.9 on 2025-12-30 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artSource', models.CharField(max_length=200)),
                ('cardType', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='CardOwnerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aquiredAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconName', models.CharField(max_length=200)),
                ('effectDescription', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='BattleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joinedBattle', models.DateTimeField(auto_now_add=True)),
                ('fled', models.BooleanField()),
                ('defeated', models.BooleanField()),
                ('deck', models.ManyToManyField(related_name='usedBy', to='MMM.card')),
                ('startingCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMM.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMM.player')),
            ],
        ),
        migrations.CreateModel(
            name='BattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='MMM.battleparticipant')),
                ('participants', models.ManyToManyField(related_name='battles', to='MMM.battleparticipant')),
                ('lootPile', models.ManyToManyField(related_name='wonIn', to='MMM.card')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='ownerHistory',
            field=models.ManyToManyField(related_name='card', to='MMM.cardownerhistory'),
        ),
        migrations.AddField(
            model_name='cardownerhistory',
            name='cardOwner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMM.player'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMM.question')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='symbols',
            field=models.ManyToManyField(related_name='onCards', to='MMM.symbol'),
        ),
    ]
