# Generated by Django 5.2.9 on 2025-12-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profilePictureSource',
            field=models.CharField(default='', max_length=200),
        ),
    ]
