# Generated by Django 5.2.9 on 2026-01-01 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0002_player_profilepicturesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inDeck', models.BooleanField(default=True)),
                ('lane', models.IntegerField(default=-1)),
                ('faceDown', models.BooleanField(default=True)),
                ('trusted', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='computerControlled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundNumber', models.IntegerField(default=-1)),
                ('freeForAll', models.BooleanField(default=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='MMM.battlehistory')),
            ],
        ),
        migrations.CreateModel(
            name='GameCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inGame', to='MMM.card')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gameCards', to='MMM.game')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardsInState', to='MMM.cardstate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usingCards', to='MMM.battleparticipant')),
            ],
        ),
    ]
