# Generated by Django 5.2.9 on 2026-01-03 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0003_cardstate_battleparticipant_computercontrolled_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('artSource', models.CharField(default='', max_length=200)),
                ('cards', models.ManyToManyField(related_name='inDecks', to='MMM.card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMM.player')),
            ],
        ),
    ]
