# Generated by Django 5.2.9 on 2026-01-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0005_alter_battlehistory_challenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='artSource',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(default='error', max_length=200),
        ),
    ]
