# Generated by Django 5.2.9 on 2026-01-04 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0006_game_artsource_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlehistory',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='MMM.player'),
        ),
    ]
