# Generated by Django 5.2.9 on 2026-01-10 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0007_alter_battlehistory_challenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleparticipant',
            name='joinedBattle',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cardownerhistory',
            name='aquiredAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
