# Generated by Django 5.2.9 on 2026-02-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0008_alter_battleparticipant_joinedbattle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleparticipant',
            name='deck',
            field=models.ManyToManyField(related_name='usedBy', to='MMM.deck'),
        ),
    ]
