# Generated by Django 5.2.9 on 2026-02-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0009_alter_battleparticipant_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleparticipant',
            name='deck',
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='deck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MMM.deck'),
            preserve_default=False,
        ),
    ]
