# Generated by Django 5.2.9 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MMM", "0010_remove_battleparticipant_deck_battleparticipant_deck"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardstate",
            name="laneOrdinal",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
