# Generated by Django 5.2.9 on 2026-02-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0011_cardstate_laneordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardstate',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
