# Generated by Django 5.2.9 on 2026-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0012_alter_cardstate_trusted_delete_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecard',
            name='cssClass',
            field=models.CharField(default='', max_length=200),
        ),
    ]
