# Generated by Django 5.2.9 on 2026-05-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMM', '0013_gamecard_cssclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleparticipant',
            name='drawnCardsAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='flippedCardsAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battleparticipant',
            name='playedCardsAmount',
            field=models.IntegerField(default=0),
        ),
    ]
